name: Mac brew

on:
  pull_request:
    paths:
      - .github/workflows/packaging-mac-brew.yml
      - downstream/mac/brew/httpie.rb

jobs:
  brew:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup brew
        run: |
          brew developer on
          brew update
      - name: Build and test the formula
        run: make brew-test
